# Generated by Django 4.1.3 on 2022-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "sitter_img",
                    models.ImageField(upload_to="", verbose_name="sitter_img"),
                ),
                ("ratting", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=120)),
                ("introduction", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(name="Pet",),
        migrations.DeleteModel(name="Users",),
    ]
