# Generated by Django 4.1.3 on 2022-11-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0002_sitterprofile_delete_pet_delete_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="sitterprofile", name="ratting",),
    ]
