# Generated by Django 4.1.3 on 2022-11-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0003_remove_sitterprofile_ratting"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitterprofile",
            name="url",
            field=models.URLField(default="index/"),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="sitter_img",
            field=models.ImageField(
                upload_to="petsitterapp/image/", verbose_name="sitter_img"
            ),
        ),
    ]
