# Generated by Django 4.1.3 on 2022-11-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0004_sitterprofile_url_alter_sitterprofile_sitter_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitterprofile",
            name="url",
            field=models.URLField(default="petsitterapp/sitter/"),
        ),
    ]
