# Generated by Django 4.1.3 on 2022-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0005_alter_sitterprofile_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitterprofile",
            name="url",
            field=models.URLField(default="petsitterapp/jason/"),
        ),
    ]
