# Generated by Django 4.1.3 on 2022-11-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0006_alter_sitterprofile_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitterprofile",
            name="sitter_img",
            field=models.ImageField(null=True, upload_to="petsitterapp/imgae/"),
        ),
    ]
