# Generated by Django 4.1.3 on 2022-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0007_alter_sitterprofile_sitter_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitterprofile",
            name="sitter_img",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
