# Generated by Django 4.1.3 on 2022-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0008_alter_sitterprofile_sitter_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitterprofile",
            name="story",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
