# Generated by Django 4.1.3 on 2022-11-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0009_sitterprofile_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("content", models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(name="Article",),
    ]
