# Generated by Django 4.1.3 on 2022-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0010_reviews_delete_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="review_id",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
