# Generated by Django 4.1.3 on 2022-11-20 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0011_reviews_review_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=120)),
                ("comment", models.TextField(max_length=2000)),
                (
                    "sitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="petsitterapp.sitterprofile",
                    ),
                ),
            ],
        ),
    ]
