# Generated by Django 4.1.3 on 2022-11-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0013_remove_comment_sitter_comment_sitterprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitterprofile",
            name="price_number",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sitterprofile",
            name="zipcode",
            field=models.TextField(max_length=20, null=True),
        ),
    ]
