# Generated by Django 4.1.3 on 2022-11-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitterapp", "0014_sitterprofile_price_number_sitterprofile_zipcode"),
    ]

    operations = [
        migrations.DeleteModel(name="Reviews",),
        migrations.AlterField(
            model_name="sitterprofile",
            name="price_number",
            field=models.IntegerField(null=True),
        ),
    ]
