# Generated by Django 4.1.3 on 2022-11-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petinfo",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
