# Generated by Django 4.1.3 on 2022-11-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_petinfo_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=120)),
            ],
        ),
    ]
