# Generated by Django 4.1.3 on 2022-11-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="tag",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
