# Generated by Django 4.1.3 on 2022-11-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_tags_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="tag",
            field=models.CharField(default="0", max_length=120),
        ),
    ]
