# Generated by Django 4.1.3 on 2022-11-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_tags_tag"),
    ]

    operations = [
        migrations.DeleteModel(name="Tags",),
    ]
